cluster.name: jinx
node.name: "Captain JiNX"

path.data: /data/data
path.logs: /data/logs

http.type: com.sonian.elasticsearch.http.jetty.JettyHttpServerTransportModule

sonian.elasticsearch.http.jetty:
	config: jetty.xml,jetty-hash-auth.xml,jetty-restrict-writes.xml

marvel.agent.exporter.es.hosts: ["jinx:bl4h0ng4@localhost:9200"]
